"""DB creation.

Revision ID: 7c5fa1086521
Revises: 
Create Date: 2023-08-19 20:13:45.523702

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7c5fa1086521'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.Column('city', sa.String(length=127), nullable=False),
                    sa.Column('name', sa.String(length=127), nullable=False),
                    sa.Column('url', sa.String(length=255), nullable=True),
                    sa.Column('metro', sa.String(length=127), nullable=True),
                    sa.Column('time_to_metro', sa.Integer(), nullable=True),
                    sa.Column('latitude', sa.Float(), nullable=True),
                    sa.Column('longitude', sa.Float(), nullable=True),
                    sa.Column('address', sa.String(length=255), nullable=True),
                    sa.Column('data_created', sa.Date(), nullable=False),
                    sa.Column('data_closed', sa.Date(), nullable=True),
                    sa.PrimaryKeyConstraint('project_id')
                    )
    op.create_table('user',
                    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
                    sa.Column('email', sa.String(length=320), nullable=False),
                    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('flat',
                    sa.Column('flat_id', sa.Integer(), nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.Column('address', sa.String(length=255), nullable=True),
                    sa.Column('floor', sa.Integer(), nullable=True),
                    sa.Column('rooms', sa.Integer(), nullable=True),
                    sa.Column('area', sa.Integer(), nullable=True),
                    sa.Column('finishing', sa.Boolean(), nullable=True),
                    sa.Column('bulk', sa.String(length=127), nullable=True),
                    sa.Column('settlement_date', sa.Date(), nullable=True),
                    sa.Column('url_suffix', sa.String(length=127), nullable=False),
                    sa.Column('data_created', sa.Date(), nullable=False),
                    sa.Column('data_closed', sa.Date(), nullable=True),
                    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
                    sa.PrimaryKeyConstraint('flat_id')
                    )
    op.create_table('price',
                    sa.Column('price_id', sa.Integer(), nullable=False),
                    sa.Column('flat_id', sa.Integer(), nullable=False),
                    sa.Column('benefit_name', sa.String(length=127), nullable=True),
                    sa.Column('benefit_description', sa.String(length=255), nullable=True),
                    sa.Column('price', sa.Integer(), nullable=False),
                    sa.Column('meter_price', sa.Integer(), nullable=True),
                    sa.Column('booking_status', sa.String(length=15), nullable=True),
                    sa.Column('data_created', sa.Date(), nullable=False),
                    sa.ForeignKeyConstraint(['flat_id'], ['flat.flat_id'], ),
                    sa.PrimaryKeyConstraint('price_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price')
    op.drop_table('flat')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('project')
    # ### end Alembic commands ###
